/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BuilderRouteImport } from './routes/builder'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ApiPublicHooksRunDueBuddiesRouteImport } from './routes/api/public/hooks/run-due-buddies'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderRoute = BuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksRunDueBuddiesRoute =
  ApiPublicHooksRunDueBuddiesRouteImport.update({
    id: '/api/public/hooks/run-due-buddies',
    path: '/api/public/hooks/run-due-buddies',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/builder': typeof BuilderRoute
  '/settings': typeof SettingsRoute
  '/api/public/hooks/run-due-buddies': typeof ApiPublicHooksRunDueBuddiesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/builder': typeof BuilderRoute
  '/settings': typeof SettingsRoute
  '/api/public/hooks/run-due-buddies': typeof ApiPublicHooksRunDueBuddiesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/builder': typeof BuilderRoute
  '/settings': typeof SettingsRoute
  '/api/public/hooks/run-due-buddies': typeof ApiPublicHooksRunDueBuddiesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/builder' | '/settings' | '/api/public/hooks/run-due-buddies'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/builder' | '/settings' | '/api/public/hooks/run-due-buddies'
  id:
    | '__root__'
    | '/'
    | '/builder'
    | '/settings'
    | '/api/public/hooks/run-due-buddies'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuilderRoute: typeof BuilderRoute
  SettingsRoute: typeof SettingsRoute
  ApiPublicHooksRunDueBuddiesRoute: typeof ApiPublicHooksRunDueBuddiesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder': {
      id: '/builder'
      path: '/builder'
      fullPath: '/builder'
      preLoaderRoute: typeof BuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/run-due-buddies': {
      id: '/api/public/hooks/run-due-buddies'
      path: '/api/public/hooks/run-due-buddies'
      fullPath: '/api/public/hooks/run-due-buddies'
      preLoaderRoute: typeof ApiPublicHooksRunDueBuddiesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuilderRoute: BuilderRoute,
  SettingsRoute: SettingsRoute,
  ApiPublicHooksRunDueBuddiesRoute: ApiPublicHooksRunDueBuddiesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
